apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name | lower}}"
  labels:
    app: "{{.Release.Name | lower}}"
spec:
  selector:
    matchLabels:
      app: "{{.Release.Name | lower}}"
  template:
    metadata:
      labels:
        app: "{{.Release.Name | lower}}"
    spec:
      containers:
      - name: "{{.Release.Name | lower}}"
        image: "{{.Release.Name | lower}}-image"
        ports:
        - containerPort: {{.Values.backend.port}}
